### ISSUE TITLE
restful?

### ISSUE THREAD

**Issue by countrdd** [MangoTools/generator-sean#4]
Can this generate the backend Restful API server?

**Comment by adidoo** [comment]
yes sean:crud-module does the trick

**Comment by countrdd** [comment]
Thanks.

I typically do a restfull and then a Single Page Application. But it sounds like I can just add the crud and use one code base. Is that correct?

Sorry. Kinda New to Nodejs/Angular..

**Comment by jean-baptiste-blanc** [comment]
That would be correct. generate a crud will create your controller  models
and route on the backend and your Angular controller and views on the
front-end. you can generate individual components using the yo generators
too.

**Comment by countrdd** [comment]
Thanks for your help...

I typically run the backend on one port and the SPA on port 80....thanks again!
